[project]
name = "dynamic-nft"
authors = ["peace <peacerichard153@gmail.com>"]
description = "A Dynamic NFT project on Stacks"
version = "0.1.0"
clarity_version = 2

[contracts.dynamic-nft]
path = "contracts/dynamic-nft.clar"
depends_on = []
